version: 3.8'
services:
  dev-db:
    image: postgres:13
    ports:
     - 5434:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES PASSWORD: 123
      POSTGRES DB: nest
      POSTGRES_HOST_AUTH_METHOD: trust
    networks:
      - sebsaNework
networks:
  sebsaNework: 